In [1]:
import numpy as np

In [2]:
def divide(A, X, Y):
    return A[:X//2,:Y//2],A[:X//2,Y//2:],A[X//2:,:Y//2],A[X//2:,Y//2:]

In [3]:
def inverse(A):
    if A is None:
        return 0
    X,Y = A.shape[0],A.shape[1]
    if X != Y:
        raise ValueError
    if X==0 or Y==0:
        raise ArithmeticError
    if X==1 and Y==1:
        return 1/A
    else:        
        A11,A12,A21,A22 = divide(A, X, Y)

        inv_A11= inverse(A11)
        
        S22 = A22 - (A21 @ inv_A11 @ A12)
        
        inv_S22 = inverse(S22)
        
        B11 = inv_A11 + inv_A11 @ A12 @ inv_S22 @A21 @ inv_A11
        B12 = -inv_A11 @ A12 @ inv_S22
        B21 = -inv_S22 @ A21 @ inv_A11
        B22 = inv_S22
        
        U = np.hstack((B11,B12))
        L = np.hstack((B21,B22))
        return np.vstack((U,L))

In [4]:
def LU(A):
    if A is None:
        return 0
    X,Y = A.shape[0],A.shape[1]
    if X != Y:
        raise ValueError
    if X==0 or Y==0:
        raise ArithmeticError
    if X==1 and Y==1:
        return np.array([[1]]), A
    else:        
        A11,A12,A21,A22 = divide(A, X, Y)

        L11, U11= LU(A11)
        
        inv_U11 = inverse(U11)
        inv_L11 = inverse(L11)
        
        S = A22 - (A21 @ inv_U11 @ inv_L11 @ A12)
        
        Ls, Us = LU(S)
        
        U12 =  inv_L11 @ A12
        U21 = np.zeros((Us.shape[0],U11.shape[1]))
        
        L12 = np.zeros((L11.shape[0],Ls.shape[1]))
        L21 = A21 @ inv_U11        
        
        Uu = np.hstack((U11,U12))
        Ul = np.hstack((U21,Us))
        U = np.vstack((Uu,Ul))
        
        Lu = np.hstack((L11,L12))
        Ll = np.hstack((L21,Ls))
        L = np.vstack((Lu,Ll))
        
        return L, U

In [18]:
def det(A):
    if A is None:
        return 0
    X,Y = A.shape[0],A.shape[1]
    if X != Y:
        raise ValueError
    if X==0 or Y==0:
        raise ArithmeticError
    if X==1 and Y==1:
        return A[0,0]
    else:        
        A11,A12,A21,A22 = divide(A, X, Y)
        L11, U11= LU(A11)
        
        inv_U11 = inverse(U11)
        inv_L11 = inverse(L11)
        
        S = A22 - (A21 @ inv_U11 @ inv_L11 @ A12)
               
        return np.prod(np.diagonal(U11))*np.prod(np.diagonal(L11))*det(S)

In [6]:
A = np.random.random((3,3))

In [7]:
inverse(A)

array([[-40.82970299,  -6.39164059,  18.15435459],
       [ 57.32901618,   6.01506264, -22.30403437],
       [-20.03711628,   0.34223945,   6.53639279]])

In [8]:
np.linalg.inv(A)

array([[-40.82970299,  -6.39164059,  18.15435459],
       [ 57.32901618,   6.01506264, -22.30403437],
       [-20.03711628,   0.34223945,   6.53639279]])

In [9]:
L, U = LU(A)

In [10]:
L, U

(array([[ 1.        ,  0.        ,  0.        ],
        [ 1.53745173,  1.        ,  0.        ],
        [ 2.9849705 , -0.05235907,  1.        ]]),
 array([[0.28299182, 0.28926812, 0.20107607],
        [0.        , 0.1392199 , 0.47505796],
        [0.        , 0.        , 0.15298958]]))

In [11]:
L@U-A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
det(A)

0.006027497808359637

In [13]:
np.linalg.det(A)

0.006027497808359637